import { createHash } from "crypto";
import { redirect } from "next/navigation";
import { caspioFetch } from "../../lib/caspio";
import { ACCOUNTS_TABLE_ID, hashPassword, setAccountSession } from "../../lib/player-auth";
export const dynamic="force-dynamic";
type Account={AccountID:number;FirstName:string;LastName:string;Email:string;EmailVerificationExpires?:string|null};type R={data:Account[]};type Params={token?:string;error?:string};
async function findByToken(token:string){const hash=createHash("sha256").update(token).digest("hex"),where=encodeURIComponent(`EmailVerificationTokenHash='${hash}'`);const r=await caspioFetch<R>(`/tables/${ACCOUNTS_TABLE_ID}/records?select=AccountID,FirstName,LastName,Email,EmailVerificationExpires&where=${where}&limit=1`);return r.data?.[0]??null;}
async function accept(formData:FormData){"use server";const token=String(formData.get("token")??"");const password=String(formData.get("password")??"");const confirm=String(formData.get("confirm")??"");if(password.length<8)redirect(`/accept-invite?token=${encodeURIComponent(token)}&error=length`);if(password!==confirm)redirect(`/accept-invite?token=${encodeURIComponent(token)}&error=match`);const account=await findByToken(token);if(!account||!account.EmailVerificationExpires||new Date(account.EmailVerificationExpires).getTime()<Date.now())redirect("/accept-invite?error=invalid");await caspioFetch(`/tables/${ACCOUNTS_TABLE_ID}/records/bulk`,{method:"PATCH",body:JSON.stringify({where:`AccountID=${account.AccountID}`,recordValues:{PasswordHash:hashPassword(password),EmailVerified:true,EmailVerificationTokenHash:null,EmailVerificationExpires:null,UpdatedAt:new Date().toISOString()}})});await setAccountSession(account.AccountID);redirect("/player");}
export default async function AcceptInvite({searchParams}:{searchParams:Promise<Params>}){const params=await searchParams;const token=params.token??"";const account=token?await findByToken(token):null;const expired=Boolean(account?.EmailVerificationExpires&&new Date(account.EmailVerificationExpires).getTime()<Date.now());if(!account||expired)return <main className="shell"><section className="hero card" style={{maxWidth:620,margin:"40px auto"}}><div className="eyebrow">TRUE APPROACH BASEBALL</div><h1>Invitation Link</h1><p className="lead">This invitation is invalid or has expired. Ask the family member who invited you to send a new invitation.</p></section></main>;return <main className="shell"><section className="hero card" style={{maxWidth:620,margin:"40px auto"}}><div className="eyebrow">TRUE APPROACH BASEBALL</div><h1>Finish Your Account</h1><p className="lead">Welcome, {account.FirstName}. Create your password to access the player connected to your invitation.</p>{params.error?<p className="errorBanner">{params.error==="match"?"The passwords do not match.":"Password must be at least 8 characters."}</p>:null}<form className="form" action={accept}><input type="hidden" name="token" value={token}/><label>Email<input value={account.Email} disabled/></label><label>Create Password<input name="password" type="password" minLength={8} required/></label><label>Confirm Password<input name="confirm" type="password" minLength={8} required/></label><button className="button primary">Create Password & Log In</button></form></section></main>;}
