import Link from "next/link";
import { redirect } from "next/navigation";
import { caspioFetch } from "../../lib/caspio";
import { ACCOUNTS_TABLE_ID, findAccountByEmail, getAccount, getAccountId, hashPassword } from "../../lib/player-auth";
export const dynamic = "force-dynamic";
type Params = { saved?: string; error?: string; from?: string };
function accountPath(params: URLSearchParams) { return `/account?${params.toString()}`; }
async function saveAccount(formData: FormData) { "use server"; const accountId = await getAccountId(); if (!accountId) redirect("/login"); const firstName=String(formData.get("firstName")??"").trim(); const lastName=String(formData.get("lastName")??"").trim(); const email=String(formData.get("email")??"").trim().toLowerCase(); const phone=String(formData.get("phone")??"").trim(); const from=String(formData.get("from")??""); const suffix=from==="coach"?"&from=coach":""; if(!firstName||!lastName||!email) redirect(`/account?error=missing${suffix}`); const existing=await findAccountByEmail(email); if(existing && existing.AccountID!==accountId) redirect(`/account?error=email${suffix}`); await caspioFetch(`/tables/${ACCOUNTS_TABLE_ID}/records?q.where=AccountID=${accountId}`,{method:"PUT",body:JSON.stringify({FirstName:firstName,LastName:lastName,Email:email,Phone:phone||null,UpdatedAt:new Date().toISOString()})}); redirect(`/account?saved=profile${suffix}`); }
async function changePassword(formData: FormData) { "use server"; const accountId=await getAccountId(); if(!accountId) redirect("/login"); const password=String(formData.get("password")??""); const confirm=String(formData.get("confirmPassword")??""); const from=String(formData.get("from")??""); const suffix=from==="coach"?"&from=coach":""; if(password.length<8) redirect(`/account?error=password-length${suffix}`); if(password!==confirm) redirect(`/account?error=password-match${suffix}`); await caspioFetch(`/tables/${ACCOUNTS_TABLE_ID}/records?q.where=AccountID=${accountId}`,{method:"PUT",body:JSON.stringify({PasswordHash:hashPassword(password),UpdatedAt:new Date().toISOString()})}); redirect(`/account?saved=password${suffix}`); }
export default async function AccountPage({searchParams}:{searchParams:Promise<Params>}) { const params=await searchParams; const accountId=await getAccountId(); if(!accountId) redirect("/login"); const account=await getAccount(accountId); if(!account) redirect("/login"); const fromCoach=params.from==="coach"; const backHref=fromCoach?"/coach":"/player"; const backLabel=fromCoach?"Coach Portal":"Player Portal"; return <main className="shell"><header className="topbar"><div><div className="eyebrow">TRUE APPROACH BASEBALL</div><h1>Account Settings</h1></div><Link className="textLink" href={backHref}>← {backLabel}</Link></header>{params.saved?<p className="successBanner">{params.saved==="password"?"Password updated.":"Account information updated."}</p>:null}{params.error?<p className="errorBanner">{params.error==="email"?"That email is already connected to another account.":params.error==="password-length"?"Password must be at least 8 characters.":params.error==="password-match"?"The passwords do not match.":"Please complete the required fields."}</p>:null}<section className="card coachSection"><div className="label">LOGIN & CONTACT</div><h2>Your Account</h2><form className="form" action={saveAccount}><input type="hidden" name="from" value={fromCoach?"coach":"player"}/><label>First Name<input name="firstName" defaultValue={account.FirstName} required/></label><label>Last Name<input name="lastName" defaultValue={account.LastName} required/></label><label>Email<input name="email" type="email" defaultValue={account.Email} required/></label><label>Phone<input name="phone" type="tel" defaultValue={account.Phone??""}/></label><button className="button primary">Save Account</button></form></section><section className="card coachSection" style={{marginTop:24}}><div className="label">SECURITY</div><h2>Change Password</h2><form className="form" action={changePassword}><input type="hidden" name="from" value={fromCoach?"coach":"player"}/><label>New Password<input name="password" type="password" minLength={8} required/></label><label>Confirm New Password<input name="confirmPassword" type="password" minLength={8} required/></label><button className="button primary">Update Password</button></form></section></main>; }
