import { issueSignedToken, presignUrl } from "@vercel/blob";
import { NextRequest } from "next/server";
import { caspioFetch, caspioRawFetch } from "../../../../lib/caspio";
import { getAccountId, getPlayerAccess } from "../../../../lib/player-auth";
import { verifySessionAccessToken } from "../../../../lib/session-access";

export const dynamic = "force-dynamic";
const SESSION_VIDEOS_TABLE_ID = "c7s9mf";
type SessionVideo={VideoID:number;VideoFile:string;SessionID:number};type VideoResponse={data:SessionVideo[]};type SessionRow={SessionID:number;PlayerID:number};type SessionResponse={data:SessionRow[]};type FileAsset={fileId:string;name:string;fullFilePath?:string};type FileSearchResponse={data:FileAsset[]};
function fileName(path:string){return decodeURIComponent(path.split("/").filter(Boolean).pop()??path);}function fallbackContentType(name:string){const extension=name.split(".").pop()?.toLowerCase();const types:Record<string,string>={avif:"image/avif",bmp:"image/bmp",gif:"image/gif",heic:"image/heic",heif:"image/heif",jpeg:"image/jpeg",jpg:"image/jpeg",png:"image/png",webp:"image/webp",mov:"video/quicktime",mp4:"video/mp4",m4v:"video/x-m4v",webm:"video/webm",pdf:"application/pdf",doc:"application/msword",docx:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",ppt:"application/vnd.ms-powerpoint",pptx:"application/vnd.openxmlformats-officedocument.presentationml.presentation",xls:"application/vnd.ms-excel",xlsx:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"};return extension?types[extension]??"application/octet-stream":"application/octet-stream";}
function parseRange(rangeHeader:string,totalLength:number){const match=/^bytes=(\d*)-(\d*)$/i.exec(rangeHeader.trim());if(!match)return null;let start:number,end:number;if(match[1]){start=Number(match[1]);end=match[2]?Number(match[2]):totalLength-1;}else if(match[2]){const suffixLength=Number(match[2]);if(!Number.isFinite(suffixLength)||suffixLength<=0)return null;start=Math.max(totalLength-suffixLength,0);end=totalLength-1;}else return null;if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||start>=totalLength||end<start)return null;return{start,end:Math.min(end,totalLength-1)};}
function sliceReadableStream(source:ReadableStream<Uint8Array>,start:number,end:number){const reader=source.getReader();let sourceOffset=0,done=false;return new ReadableStream<Uint8Array>({async pull(controller){if(done){controller.close();return;}while(true){const result=await reader.read();if(result.done){done=true;controller.close();return;}const chunk=result.value;const chunkStart=sourceOffset;const chunkEnd=sourceOffset+chunk.byteLength-1;sourceOffset+=chunk.byteLength;if(chunkEnd<start)continue;if(chunkStart>end){done=true;await reader.cancel();controller.close();return;}const from=Math.max(start-chunkStart,0);const to=Math.min(end-chunkStart+1,chunk.byteLength);if(to>from)controller.enqueue(chunk.subarray(from,to));if(chunkEnd>=end){done=true;await reader.cancel();controller.close();}return;}},async cancel(){done=true;await reader.cancel();}});}
async function privateBlobRedirect(pathname:string){const validUntil=Date.now()+10*60*1000;const token=await issueSignedToken({pathname,operations:["get"],validUntil});const{presignedUrl}=await presignUrl(token,{operation:"get",pathname,access:"private",validUntil});return Response.redirect(presignedUrl,302);}
async function canViewSession(sessionId:number,accessToken:string|null){const sessionResult=await caspioFetch<SessionResponse>(`/tables/o1u972/records?select=SessionID,PlayerID&where=SessionID=${sessionId}&limit=1`);const session=sessionResult.data?.[0];if(!session)return false;const guest=verifySessionAccessToken(accessToken);if(guest&&guest.sessionId===session.SessionID&&guest.playerId===session.PlayerID)return true;const accountId=await getAccountId();if(!accountId)return false;const access=await getPlayerAccess(accountId);return access.some(row=>row.PlayerID===session.PlayerID);}
export async function GET(request:NextRequest,{params}:{params:Promise<{id:string}>}){const{id}=await params;const videoId=Number(id);if(!Number.isInteger(videoId)||videoId<=0)return new Response("Invalid content",{status:400});try{const recordResult=await caspioFetch<VideoResponse>(`/tables/${SESSION_VIDEOS_TABLE_ID}/records?select=VideoID,VideoFile,SessionID&where=VideoID=${videoId}&limit=1`);const video=recordResult.data?.[0];if(!video?.VideoFile)return new Response("Content not found",{status:404});if(!(await canViewSession(video.SessionID,request.nextUrl.searchParams.get("access"))))return new Response("Unauthorized",{status:401});if(video.VideoFile.startsWith("session-content/"))return await privateBlobRedirect(video.VideoFile);const name=fileName(video.VideoFile);const searchResult=await caspioFetch<FileSearchResponse>(`/fileAssets/files/search?name=${encodeURIComponent(name)}`);const file=searchResult.data?.find(item=>item.fullFilePath===video.VideoFile)??searchResult.data?.find(item=>item.name===name)??searchResult.data?.[0];if(!file?.fileId)return new Response("Stored file not found",{status:404});const range=request.headers.get("range");const caspioResponse=await caspioRawFetch(`/fileAssets/files/${file.fileId}`,{headers:{Accept:"*/*",...(range?{Range:range}:{})}});if(!caspioResponse.ok&&caspioResponse.status!==206)return new Response("Unable to load content",{status:502});const headers=new Headers();for(const key of["content-type","content-length","content-range","accept-ranges","etag","last-modified"]){const value=caspioResponse.headers.get(key);if(value)headers.set(key,value);}const inferredType=fallbackContentType(name);const caspioType=headers.get("content-type")?.toLowerCase()??"";if(!caspioType||caspioType==="application/octet-stream"||caspioType==="binary/octet-stream")headers.set("content-type",inferredType);headers.set("accept-ranges","bytes");headers.set("cache-control","private, max-age=300");if(caspioResponse.status===206||!range)return new Response(caspioResponse.body,{status:caspioResponse.status,headers});const totalLength=Number(caspioResponse.headers.get("content-length"));if(!Number.isFinite(totalLength)||totalLength<=0||!caspioResponse.body)return new Response(caspioResponse.body,{status:200,headers});const parsedRange=parseRange(range,totalLength);if(!parsedRange)return new Response(null,{status:416,headers:{"content-range":`bytes */${totalLength}`,"accept-ranges":"bytes"}});headers.set("content-range",`bytes ${parsedRange.start}-${parsedRange.end}/${totalLength}`);headers.set("content-length",String(parsedRange.end-parsedRange.start+1));return new Response(sliceReadableStream(caspioResponse.body,parsedRange.start,parsedRange.end),{status:206,headers});}catch(error){console.error("Content preview failed",error);return new Response("Unable to load content",{status:500});}}
